//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidHub.Infrastructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieDbEntities : DbContext
    {
        public MovieDbEntities()
            : base("name=MovieDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MOVIE> MOVIEs { get; set; }
        public virtual DbSet<PATH_TYPE> PATH_TYPE { get; set; }
        public virtual DbSet<WEB_SITE> WEB_SITE { get; set; }
        public virtual DbSet<MOVIE_LINK> MOVIE_LINK { get; set; }
        public virtual DbSet<PERSON> People { get; set; }
        public virtual DbSet<PERSON_ROLE> PERSON_ROLE { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<GENRE> GENREs { get; set; }
        public virtual DbSet<MOVIE_GENRE> MOVIE_GENRE { get; set; }
    }
}
