//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidHub.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIE
    {
        public MOVIE()
        {
            this.MOVIE_LINK = new HashSet<MOVIE_LINK>();
            this.MOVIE_GENRE = new HashSet<MOVIE_GENRE>();
            this.PERSON_ROLE1 = new HashSet<PERSON_ROLE>();
        }
    
        public int MOVIE_ID { get; set; }
        public string TITLE { get; set; }
        public string MOVIE_POSTER_PATH { get; set; }
        public string MOVIE_DESC { get; set; }
        public string LAST_MOD_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATE { get; set; }
    
        public virtual ICollection<MOVIE_LINK> MOVIE_LINK { get; set; }
        public virtual ICollection<MOVIE_GENRE> MOVIE_GENRE { get; set; }
        public virtual ICollection<PERSON_ROLE> PERSON_ROLE1 { get; set; }
    }
}
