//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidHub.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_ROLE
    {
        public int PERSON_ROLE_ID { get; set; }
        public int PERSON_ID { get; set; }
        public int ROLE_ID { get; set; }
        public string LAST_MOD_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATE { get; set; }
        public int MOVIE_ID { get; set; }
    
        public virtual ROLE ROLE { get; set; }
        public virtual PERSON PERSON1 { get; set; }
        public virtual MOVIE MOVIE1 { get; set; }
    }
}
