//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidHub.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public PERSON()
        {
            this.PERSON_ROLE1 = new HashSet<PERSON_ROLE>();
        }
    
        public string LAST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public int PERSON_ID { get; set; }
        public string LAST_MOD_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_MOD_DATE { get; set; }
    
        public virtual ICollection<PERSON_ROLE> PERSON_ROLE1 { get; set; }
    }
}
