//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidHub.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_SITE
    {
        public WEB_SITE()
        {
            this.MOVIE_LINK = new HashSet<MOVIE_LINK>();
        }
    
        public int WEB_SITE_ID { get; set; }
        public string WEB_SITE_NAME { get; set; }
        public string WEB_URL { get; set; }
    
        public virtual ICollection<MOVIE_LINK> MOVIE_LINK { get; set; }
    }
}
